[supabase]
url = "https://frxhylrlaiaxlpkdsayg.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZyeGh5bHJsYWlheGxwa2RzYXlnIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1Njk3NDY0OCwiZXhwIjoyMDcyNTUwNjQ4fQ.j6UJ3rFlLVDs0WeUg0DxYWIeHrkY2sjNixMAGFkbxkg"
